config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#show'

  get 'sign-in', to: 'session#new', as: :new_session
  resource :session, only: %i[create destroy], controller: :session
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end

  def create
    token = IdentityPlatform::Token.load session_params[:token]

    if token.valid? && sign_in_token_user(token)
      redirect_to session.fetch :after_sign_in_path, root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    sign_out_user
    redirect_to sign_in_path
  end

  private

  def session_params
    params.require(:session).permit :token
  end

  def sign_in_token_user(token, scope: :default)
    user = User.from_identity_token token
    warden.set_user(user, scope: scope)
  end

  def sign_out_user(scope: nil)
    if scope
      warden.logout(scope)
      warden.clear_strategies_cache!(scope: scope)
    else
      warden.logout
      warden.clear_strategies_cache!
    end
  end
end

app/views/session/new.html.erb
<section id="auth-container" data-controller="sign-in" class="w-full content-center">
  <%= form_with url: session_path, scope: :session, data: { sign_in_target: "sessionForm" } do |f| %>
    <%= f.hidden_field :token, data: { sign_in_target: "token" } %>
  <% end %>
</section>